In [38]:
import numpy as np
import matplotlib.pyplot as plt
import torch
from PIL import Image
import torchvision.transforms as T

In [39]:
torch.cuda.is_available()

True

In [40]:
a = torch.ones(3)

In [41]:
a

tensor([1., 1., 1.])

In [42]:
points =torch.tensor([  [4.0, 1.0],
                        [5.0, 3.0],
                        [2.0, 1.0]])

In [43]:
points[0]

tensor([4., 1.])

In [44]:
some_list = list([1,3,6,8,0,2])

In [45]:
some_list[1:6:2]

[3, 8, 2]

In [46]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [47]:
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [48]:
img_t = torch.randn(3, 5, 5) # shape [channels, rows, columns]
img_t

tensor([[[-0.0745, -1.2942,  0.7413, -1.0647, -0.1722],
         [ 1.3152,  1.0373, -0.4153,  0.1359,  2.1957],
         [-0.2576,  1.1405, -0.0856, -0.8304, -1.2877],
         [-0.4504, -0.0298,  1.3632,  0.0224, -1.7027],
         [ 1.1194, -0.3954, -1.0784,  0.1682, -1.2392]],

        [[ 1.1497,  1.3253,  0.3355, -1.4937,  1.7059],
         [ 0.3990, -0.4719, -0.0327, -0.4155,  1.3604],
         [-1.1906, -1.2046, -0.4647,  0.9386,  0.5840],
         [ 0.7840, -1.0118,  2.2855,  1.0181,  0.6620],
         [ 0.2757,  1.0221,  0.3514, -0.2175,  0.0521]],

        [[ 0.0032,  0.9722,  1.9846, -1.7369, -0.3320],
         [-0.6870, -1.0685,  0.0477,  0.7692, -0.9486],
         [ 0.4392, -0.2230,  0.9328, -0.6943, -0.6642],
         [-0.0538, -0.6148, -0.1865, -0.0824,  1.9527],
         [ 0.6139,  1.2573, -0.1927,  0.0479,  1.2380]]])

In [49]:
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [50]:
batch_t = torch.randn(2, 3, 5, 5) # shape [batch, channels, rows, columns]

In [51]:
transform = T.ToPILImage()

In [52]:
img = transform(img_t)
img.show()

In [53]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [54]:
img = transform(batch_gray_naive[0])
img.show()

In [55]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
unsqueezed_weights

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]])

In [56]:
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [57]:
batch_weights

tensor([[[[-0.3885,  0.0378,  0.1902,  0.0097,  0.1911],
          [-0.0167,  0.3938, -0.1955,  0.0814, -0.3002],
          [ 0.1020, -0.0648, -0.1026, -0.3090,  0.0902],
          [-0.1208, -0.1075, -0.0823,  0.1882, -0.3127],
          [-0.0025, -0.1295, -0.1639, -0.2463, -0.2334]],

         [[-0.0048, -0.8753,  0.2951, -0.5679,  1.1571],
          [-0.3370,  0.4018,  0.1493,  0.1484, -0.9265],
          [-0.7740,  0.9008, -0.0831, -0.6958, -0.4438],
          [-0.8209,  0.0203, -0.9867,  0.4945,  0.6885],
          [-0.9959, -0.7588, -0.7262,  0.0666, -0.3915]],

         [[-0.0140, -0.0217, -0.0613,  0.0060, -0.0359],
          [-0.1591,  0.0627, -0.0194, -0.1414,  0.0645],
          [-0.0191, -0.0285,  0.0655, -0.0274, -0.0823],
          [-0.0179,  0.0351, -0.0088,  0.0287, -0.0468],
          [-0.0200,  0.0182, -0.1630,  0.0693,  0.0532]]],


        [[[-0.2263, -0.2256,  0.0162,  0.0022, -0.0338],
          [-0.0336,  0.1769, -0.0664, -0.5320,  0.0542],
          [-0.2304, -0.

In [58]:
img_gray_weighted_fancy = torch.einsum('...chw,c->...hw', img_t, weights)
batch_gray_weighted_fancy = torch.einsum('...chw,c->...hw', batch_t, weights)
batch_gray_weighted_fancy.shape

torch.Size([2, 5, 5])

In [59]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
weights_named

C:\Users\tayfununal\AppData\Local\Temp\ipykernel_3036\2371314847.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at ..\c10/core/TensorImpl.h:1761.)
  weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [60]:
img_named = img_t.refine_names(..., 'channels', 'rows', 'columns')
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns')
print("img named:", img_named.shape, img_named.names)
print("batch named:", batch_named.shape, batch_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [61]:
weights_aligned = weights_named.align_as(img_named)
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [62]:
gray_named = (img_named * weights_aligned).sum('channels')
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [63]:
a = torch.tensor( [[[1., 1],
                    [1., 1.]],  
                   [[2., 2.],
                    [2., 2.]],
                   [[3., 3.],
                    [3., 3.]]])
a

tensor([[[1., 1.],
         [1., 1.]],

        [[2., 2.],
         [2., 2.]],

        [[3., 3.],
         [3., 3.]]])

In [64]:
a_named = a.refine_names(..., 'channels', 'row', 'column')

In [65]:
a_named

tensor([[[1., 1.],
         [1., 1.]],

        [[2., 2.],
         [2., 2.]],

        [[3., 3.],
         [3., 3.]]], names=('channels', 'row', 'column'))

In [66]:
a_named.sum('column')

tensor([[2., 2.],
        [4., 4.],
        [6., 6.]], names=('channels', 'row'))

In [67]:
weights_named = torch.tensor([5, 3, 2], names=['channels'])
weights_named.shape

torch.Size([3])

In [68]:
weights_aligned = weights_named.align_as(img_named)
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [69]:
gray_named = (a * weights_aligned).sum('channels')
gray_named.shape, gray_named.names

(torch.Size([2, 2]), ('rows', 'columns'))

In [70]:
gray_named

tensor([[17., 17.],
        [17., 17.]], names=('rows', 'columns'))

In [71]:
gray_named = (img_named[..., :3] * weights_aligned).sum('channels')
gray_named

tensor([[ 3.0831e+00, -5.5060e-01,  8.6825e+00],
        [ 6.3988e+00,  1.6341e+00, -2.0792e+00],
        [-3.9813e+00,  1.6427e+00,  4.3648e-02],
        [-7.8782e-03, -4.4142e+00,  1.3300e+01],
        [ 7.6520e+00,  3.6037e+00, -4.7231e+00]], names=('rows', 'columns'))

In [72]:
a.transpose(0,1)

tensor([[[1., 1.],
         [2., 2.],
         [3., 3.]],

        [[1., 1.],
         [2., 2.],
         [3., 3.]]])

In [73]:
b = torch.tensor([[1,2],[3,4]])
b

tensor([[1, 2],
        [3, 4]])

In [74]:
b.transpose(0,1)

tensor([[1, 3],
        [2, 4]])

In [75]:
points = torch.tensor([[4.0, 1.0, 3.0], [5.0, 3.0, 3.0], [2.0, 1.0, 3.0]])

In [76]:
points.stride()

(3, 1)

In [77]:
a = torch.rand(4,4)
a

tensor([[0.1226, 0.1809, 0.3305, 0.3666],
        [0.2844, 0.3471, 0.0365, 0.2402],
        [0.9968, 0.6781, 0.0190, 0.5902],
        [0.4594, 0.6630, 0.6704, 0.3798]])

In [78]:
#doktora tezinde kullanabilirim
a = a.reshape(2,2,2,2)
b = a.transpose(2,1)
c = b.reshape(4,2,2)
c

tensor([[[0.1226, 0.1809],
         [0.2844, 0.3471]],

        [[0.3305, 0.3666],
         [0.0365, 0.2402]],

        [[0.9968, 0.6781],
         [0.4594, 0.6630]],

        [[0.0190, 0.5902],
         [0.6704, 0.3798]]])

In [79]:
y_1 = c[0].reshape(4,1)
y_1

tensor([[0.1226],
        [0.1809],
        [0.2844],
        [0.3471]])

In [80]:
points_gpu = points.to(device='cuda')

In [81]:
points_gpu

tensor([[4., 1., 3.],
        [5., 3., 3.],
        [2., 1., 3.]], device='cuda:0')

In [82]:
x = torch.tensor([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
x.shape

torch.Size([2, 5])

In [83]:
points = torch.tensor([[8.0, 1.0, 3.0], [5.0, 3.0, 3.0], [7.0, 1.0, 3.0]])

In [84]:
torch.save(points, './ourpoints.t')

In [85]:
points_return = torch.load('./ourpoints.t')
points_return.shape

torch.Size([3, 3])

In [86]:
points_return

tensor([[8., 1., 3.],
        [5., 3., 3.],
        [7., 1., 3.]])

In [87]:
import h5py

In [88]:
f = h5py.File('./h5py_points.hdf5','w')
dataset = f.create_dataset('coords', data = points.numpy())
f.close()

In [89]:
f = h5py.File('./h5py_points.hdf5', 'r')
dset = f['coords']
last_points = dset[-2:]
f.close()

In [90]:
last_points

array([[5., 3., 3.],
       [7., 1., 3.]], dtype=float32)

In [101]:
x_1 = torch.tensor(list(range(9)))

In [104]:
y_1 = x_1.view(3, 3)
c = y_1[1:,1:]
y_1

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [141]:
a = torch.tensor([2, 4, 6])
b = a.add_(10)

In [142]:
a is b

True